In [5]:
import numpy as np

### Creating numpy arrays

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1.1,2.4],[3.6,4.5]])
arr3 = np.array([[[1,2,3,4,5],[5,6,7,8,9],[9,1,2,3,4]]])
arr4 = np.array([[[3,4,5],[2,4,5]],
                 [[4,5,6],[7,8,9]],
                 [[5,3,2] ,[3,6,3]]])
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[1 2 3 4 5]
[[1.1 2.4]
 [3.6 4.5]]
[[[1 2 3 4 5]
  [5 6 7 8 9]
  [9 1 2 3 4]]]
[[[3 4 5]
  [2 4 5]]

 [[4 5 6]
  [7 8 9]]

 [[5 3 2]
  [3 6 3]]]


In [ ]:
print(arr1.dtype)
print(arr2.dtype)
print(f'dimension of arr1: {arr1.ndim}')#1D
print(f'shape of arr1 :  {arr1.shape}')
print(f'size of arr1:{arr1.size}')#number of elements in array
print()
print(f'dimension of arr2: {arr2.ndim}') #2D
print(f'shape of arr2 : {arr2.shape}')
print(f'size of arr1:{arr2.size}')
print()
print(f'dimension of arr3: {arr3.ndim}')#3D
print(f'shape of arr3 : {arr3.shape}')
print(f'size of arr1:{arr3.size}')
print()
print(f'dimension of arr4: {arr4.ndim}')#3D
print(f'shape of arr4 : {arr4.shape}')
print(f'size of arr1:{arr4.size}')

int64
float64
dimension of arr1: 1
shape of arr1 :  (5,)
size of arr1:5

dimension of arr2: 2
shape of arr2 : (2, 2)
size of arr1:4

dimension of arr3: 3
shape of arr3 : (1, 3, 5)
size of arr1:15

dimension of arr4: 3
shape of arr4 : (3, 2, 3)
size of arr1:18


### Numpy functions

In [38]:
arr0 = np.zeros((3,2,3))
arr_one = np.ones((1,3,5))
full_arr = np.full((2,2) , 4)
a1 = np.arange(1,10,2)#crate array in specific range ,here 2 is the gap between two numbers
a2=np.linspace(1,5,3)#create array between specific range with evenly distance , here 3 is that number of element i want
a3 = np.eye(3)# create identity matrix


print(arr0)
print()
print(arr_one)
print()
print(full_arr)
print()
print(a1)
print()
print(a2)
print()
print(a3)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

[[4 4]
 [4 4]]

[1 3 5 7 9]

[1. 3. 5.]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Random numbers

In [ ]:
a4 = np.random.rand(2,3)#crate random element of array between 0-1 (float values)
a5 = np.random.randint(2,8)# create random integer from given range
a6 = np.random.randn(2,3)#create random numbers in normal distribution  (-infinite to +infinite)
a7 = np.random.choice(range(1,20) , 5)#return random numbers from given set or range 

print(a4)
print(a5)
print(a6)
print(a7)

[[0.90086107 0.07675531 0.57846852]
 [0.43748804 0.39141086 0.755908  ]]
5
[[-1.69714537  1.72897466 -0.27368562]
 [ 0.46632719 -0.46131117 -0.7474403 ]]
[17 14 15 14  2]


### Mathematical functions

In [ ]:
a1 = [7,8,9]
a2 = [4,5,6]

print(f"addition: {np.add(a1 ,a2)}")
print(f"subtraction: {np.subtract(a1 ,a2)}")
print(f"multiplication: {np.multiply(a1 ,a2)}")
print(f"division: {np.divide(a1 ,a2)}")
print(f"power: {np.pow(a1 ,2)}")
print(f"sqrt: {np.sqrt(a2)}")

print(f"sum: {np.sum(a1)}")#addition of all elements in one array





addition: [11 13 15]
subtraction: [3 3 3]
multiplication: [28 40 54]
division: [1.75 1.6  1.5 ]
power: [49 64 81]
sqrt: [2.         2.23606798 2.44948974]
sum: 24


### statistical function

In [51]:
a1 = [2,4,65,23,90,-5,5]

print(f'mean:{np.mean(a1)}')
print(f'median:{np.median(a1)}')
print(f'standard deviation:{np.std(a1)}')
print(f'variance:{np.var(a1)}')
print(f'minium :{np.min(a1)}')
print(f'maxium:{np.max(a1)}')
print(f'percentile:{np.percentile(a1,33)}')



mean:26.285714285714285
median:5.0
standard deviation:33.990394801701115
variance:1155.3469387755101
minium :-5
maxium:90
percentile:3.96


### comparison & logical function

In [59]:
arr = np.array([5,10,15,20,25])

print(np.where(arr%2 == 0 , arr , 0))
print(np.any(arr%2 == 0)) # return true if any one element satisfy condition
print(np.all(arr%2 == 0)) # return true if all element satisfy condition
print(np.logical_and(arr> 8, arr < 18))
print(np.logical_or(arr > 8, arr < 18))

[ 0 10  0 20  0]
True
False
[False  True  True False False]
[ True  True  True  True  True]


### sorting and searching

In [62]:
a = np.array([29,54,78,-3,76,2,4,2])

print(f'sorted array: {np.sort(a)}')
print(f"maxiumum element's idx:{np.argmax(a)}")
print(f"minimum number's index :{np.argmin(a)}")
print(f'unique values of array : {np.unique(a)}')


sorted array: [-3  2  2  4 29 54 76 78]
maxiumum element's idx:2
minimum number's index :3
unique values of array : [-3  2  4 29 54 76 78]


### linear algebra

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c= np.array([[1,2],[3,4]])

print(f'dot product : {np.dot(a,b)}')  #1*4 + 2*5 + 3*6 = 32
print(f"determinate:{np.linalg.det(c)}")
print(f"inverse natrix: {np.linalg.inv(c)}")

dot product : 32
determinate:-2.0000000000000004
inverse natrix: [[-2.   1. ]
 [ 1.5 -0.5]]


In [70]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A, B))


[[19 22]
 [43 50]]


In [71]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.matmul(A, B))

[[19 22]
 [43 50]]


### View of Array in NumPy

In [75]:

arr = np.array([2, 4, 6, 8, 10])
v = arr.view()

print("Original ID:", id(arr))
print("View ID:    ", id(v))

arr[0] = 12 

print("Original array:", arr)
print("View array:    ", v)

Original ID: 125252994264848
View ID:     125252996056624
Original array: [12  4  6  8 10]
View array:     [12  4  6  8 10]


### Copy of Array in NumPy

In [76]:

arr = np.array([2, 4, 6, 8, 10])
c = arr.copy()

print("Original ID:", id(arr))
print("Copy ID:    ", id(c))

arr[0] = 12
print("Original array:", arr)
print("Copy array:    ", c)

Original ID: 125252994268208
Copy ID:     125252779659536
Original array: [12  4  6  8 10]
Copy array:     [ 2  4  6  8 10]


### reshapeing and modifying arrays

##### Reshape

In [84]:
a = np.array([1, 2, 3, 4, 5, 6])

a.reshape(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

flatten() – Convert to 1D (copy) . 
Converts array to 1D array and returns a copy.

In [86]:
a = np.array([[1, 2],
              [3, 4]])

b = a.flatten()
print(b)

[1 2 3 4]


ravel() - same as flatten but it return view not copy

In [87]:
a = np.array([[1, 2],
              [3, 4]])

b = a.ravel()
print(b)

[1 2 3 4]


Transpose()

In [88]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(np.transpose(a))


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


resize

In [90]:
a = np.array([1, 2, 3, 4])
a.resize(2, 3)
print(a)


[[1 2 3]
 [4 0 0]]


# practice problems

#### 1.Create a 1D NumPy array containing numbers from 10 to 50.

In [79]:
a = np.arange(11,51,1)
print(a)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### 2.Create a 3×3 array filled with zeros.

In [81]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


 #### 3.Create a 4×4 identity matrix.

In [82]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 4.Create an array of 5 random integers between 1 and 100.

In [83]:
a = np.random.randint(1,100,5)
print(a)

[24 60 79 24 67]
